set @today = current_date();
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (1,1000,date_add(@today, interval -10 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (2,950,date_add(@today, interval -9 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (3,1125,date_add(@today, interval -8 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (4,500,date_add(@today, interval -7 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (5,1500,date_add(@today, interval -6 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (6,550,date_add(@today, interval -5 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (7,800,date_add(@today, interval -4 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (8,1475,date_add(@today, interval -3 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (9,850,date_add(@today, interval -2 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (10,625,date_add(@today, interval -1 day),1);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (11,900,date_add(@today, interval -72 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (12,950,date_add(@today, interval -71 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (13,800,date_add(@today, interval -70 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (14,925,date_add(@today, interval -69 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (15,725,date_add(@today, interval -48 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (16,850,date_add(@today, interval -47 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (17,750,date_add(@today, interval -46 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (18,700,date_add(@today, interval -45 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (19,1000,date_add(@today, interval -24 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (20,975,date_add(@today, interval -23 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (21,1225,date_add(@today, interval -22 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (22,1500,date_add(@today, interval -21 hour),2);
insert into hourly_electricity(id,generated_electricity,reading_at,panel_id) values (23,1800,@today,2);
